use std::path::PathBuf;

use clap::Args as ClapArgs;

use crate::output;

use super::context;

/// SemVer range of configuration-generating growl versions accepted by this binary.
const COMPATIBLE_GROWL_VERSION_RANGE: &str = ">=0.1.0, <0.2.0";

#[derive(Debug, ClapArgs)]
pub struct ValidateArgs {
    #[arg(long, help = "YAML configuration file")]
    pub config: Option<PathBuf>,
}

pub fn validate(args: &ValidateArgs) -> Result<u8, String> {
    let config_context = context::load(args.config.as_deref())?;
    let mut diagnostics = growl_core::validation::lint_config::lint(config_context.config());
    diagnostics.extend(version_diagnostics(config_context.config().growl_version.as_deref()));
    output::print_diagnostics(&diagnostics);

    Ok(if diagnostics.iter().any(|diagnostic| diagnostic.is_error()) { 1 } else { 0 })
}

fn version_diagnostics(config_version: Option<&str>) -> Vec<growl_core::diagnostic::Diagnostic> {
    let Some(config_version) = config_version else {
        return vec![growl_core::diagnostic::Diagnostic::error(
            "config-growl-version-missing",
            Some("growl_version".to_string()),
            "configuration must define growl_version",
        )];
    };

    let compatible = semver::VersionReq::parse(COMPATIBLE_GROWL_VERSION_RANGE)
        .ok()
        .zip(semver::Version::parse(config_version).ok())
        .is_some_and(|(range, configured)| range.matches(&configured));
    if compatible {
        Vec::new()
    } else {
        vec![growl_core::diagnostic::Diagnostic::error(
            "config-growl-version-incompatible",
            Some("growl_version".to_string()),
            format!(
                "configuration was generated by growl {config_version}, which is not compatible with this binary (compatible version range: {COMPATIBLE_GROWL_VERSION_RANGE})"
            ),
        )]
    }
}

#[cfg(test)]
mod tests {
    use super::version_diagnostics;

    #[test]
    fn accepts_versions_in_the_compatible_line() {
        assert!(version_diagnostics(Some("0.1.9")).is_empty());
        assert!(version_diagnostics(Some("0.1.0")).is_empty());
    }

    #[test]
    fn rejects_missing_and_incompatible_versions() {
        assert_eq!(version_diagnostics(None)[0].code, "config-growl-version-missing");
        assert_eq!(version_diagnostics(Some("0.2.0"))[0].code, "config-growl-version-incompatible");
    }
}
